# What do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M # 20Gi

---
# How do we implement it

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb2/"
    type: DirectoryOrCreate